/**
 * GENERATED FILE — do not edit by hand.
 * Regenerate with:  pnpm --filter @dofortech/pretty-ui-docs toc
 *
 * The h2/h3 headings of every MDX page, keyed by route, so the "On this page"
 * rail can be server-rendered from a layout that cannot see the page. It is a
 * SEED, not the source of truth — components/toc.tsx reconciles it against the
 * rendered headings on mount, which is what absorbs a stale entry between a
 * heading rename and the next run of this script.
 */
export type TocHeading = { id: string; text: string; depth: 2 | 3 };

export const TOC: Record<string, TocHeading[]> = {
  "/components/accordion": [
    { id: "import", text: "Import", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "divided", text: "Divided", depth: 3 },
    { id: "contained", text: "Contained", depth: 3 },
    { id: "several-panels-at-once", text: "Several panels at once", depth: 3 },
    { id: "controlled", text: "Controlled", depth: 3 },
    { id: "disabled-item", text: "Disabled item", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "motion", text: "Motion", depth: 3 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "accordionroot", text: "Accordion.Root", depth: 3 },
    { id: "accordionitem", text: "Accordion.Item", depth: 3 },
    { id: "accordionheader", text: "Accordion.Header", depth: 3 },
    { id: "accordiontrigger", text: "Accordion.Trigger", depth: 3 },
    { id: "accordionpanel", text: "Accordion.Panel", depth: 3 },
  ],
  "/components/avatar": [
    { id: "import", text: "Import", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "sizes", text: "Sizes", depth: 3 },
    { id: "shape", text: "Shape", depth: 3 },
    { id: "variants-and-tones", text: "Variants and tones", depth: 3 },
    { id: "when-the-image-is-missing", text: "When the image is missing", depth: 3 },
    { id: "groups", text: "Groups", depth: 3 },
    { id: "presence-and-badges", text: "Presence and badges", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "motion", text: "Motion", depth: 3 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "avatarroot", text: "Avatar.Root", depth: 3 },
    { id: "avatarimage", text: "Avatar.Image", depth: 3 },
    { id: "avatarfallback", text: "Avatar.Fallback", depth: 3 },
    { id: "avatarbadge", text: "Avatar.Badge", depth: 3 },
    { id: "avatargroup", text: "Avatar.Group", depth: 3 },
  ],
  "/components/button": [
    { id: "import", text: "Import", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "tones", text: "Tones", depth: 3 },
    { id: "sizes", text: "Sizes", depth: 3 },
    { id: "loading", text: "Loading", depth: 3 },
    { id: "icon-only", text: "Icon-only", depth: 3 },
    { id: "rendering-as-another-element", text: "Rendering as another element", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
  ],
  "/components/checkbox": [
    { id: "import", text: "Import", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "sizes", text: "Sizes", depth: 3 },
    { id: "indeterminate", text: "Indeterminate", depth: 3 },
    { id: "groups", text: "Groups", depth: 3 },
    { id: "disabled", text: "Disabled", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "checkbox-1", text: "Checkbox", depth: 3 },
    { id: "checkboxgroup", text: "CheckboxGroup", depth: 3 },
  ],
  "/components/checkbox-group": [
    { id: "import", text: "Import", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "labelling", text: "Labelling", depth: 3 },
    { id: "rendering-as-a-native-button", text: "Rendering as a native button", depth: 3 },
    { id: "orientation", text: "Orientation", depth: 3 },
    { id: "controlled", text: "Controlled", depth: 3 },
    { id: "parent-checkbox", text: "Parent checkbox", depth: 3 },
    { id: "nested-parent-checkboxes", text: "Nested parent checkboxes", depth: 3 },
    { id: "form-integration", text: "Form integration", depth: 3 },
    { id: "disabled", text: "Disabled", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "checkboxgroup", text: "CheckboxGroup", depth: 3 },
    { id: "checkbox", text: "Checkbox", depth: 3 },
  ],
  "/components/collapsible": [
    { id: "import", text: "Import", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "plain", text: "Plain", depth: 3 },
    { id: "contained", text: "Contained", depth: 3 },
    { id: "controlled", text: "Controlled", depth: 3 },
    { id: "a-different-marker", text: "A different marker", depth: 3 },
    { id: "disabled", text: "Disabled", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "motion", text: "Motion", depth: 3 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "collapsibleroot", text: "Collapsible.Root", depth: 3 },
    { id: "collapsibletrigger", text: "Collapsible.Trigger", depth: 3 },
    { id: "collapsiblepanel", text: "Collapsible.Panel", depth: 3 },
  ],
  "/components/color-picker": [
    { id: "import", text: "Import", depth: 2 },
    { id: "anatomy", text: "Anatomy", depth: 2 },
    { id: "the-value", text: "The value", depth: 2 },
    { id: "formats", text: "Formats", depth: 3 },
    { id: "opacity", text: "Opacity", depth: 3 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "swatches-only", text: "Swatches only", depth: 3 },
    { id: "controlled", text: "Controlled", depth: 3 },
    { id: "the-eyedropper", text: "The eyedropper", depth: 3 },
    { id: "triggers", text: "Triggers", depth: 3 },
    { id: "in-a-form", text: "In a form", depth: 3 },
    { id: "disabled", text: "Disabled", depth: 3 },
    { id: "keyboard", text: "Keyboard", depth: 2 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "colorpickerroot", text: "ColorPicker.Root", depth: 3 },
    { id: "colorpickertrigger", text: "ColorPicker.Trigger", depth: 3 },
    { id: "colorpickerpopup", text: "ColorPicker.Popup", depth: 3 },
    { id: "colorpickerpanel", text: "ColorPicker.Panel", depth: 3 },
    { id: "colorpickerrow", text: "ColorPicker.Row", depth: 3 },
    { id: "colorpickerarea", text: "ColorPicker.Area", depth: 3 },
    { id: "colorpickerhueslider", text: "ColorPicker.HueSlider", depth: 3 },
    { id: "colorpickeralphaslider", text: "ColorPicker.AlphaSlider", depth: 3 },
    { id: "colorpickerswatches", text: "ColorPicker.Swatches", depth: 3 },
    { id: "colorpickerswatch", text: "ColorPicker.Swatch", depth: 3 },
    { id: "colorpickerpreview", text: "ColorPicker.Preview", depth: 3 },
    { id: "colorpickervalue", text: "ColorPicker.Value", depth: 3 },
    { id: "colorpickerformat", text: "ColorPicker.Format", depth: 3 },
    { id: "colorpickerinput", text: "ColorPicker.Input", depth: 3 },
    { id: "colorpickereyedropper", text: "ColorPicker.EyeDropper", depth: 3 },
    { id: "colorpickerhiddeninput", text: "ColorPicker.HiddenInput", depth: 3 },
    { id: "default_swatches", text: "DEFAULT_SWATCHES", depth: 3 },
  ],
  "/components/dialog": [
    { id: "import", text: "Import", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "a-close-button-in-the-corner", text: "A close button in the corner", depth: 3 },
    { id: "footer-alignment", text: "Footer alignment", depth: 3 },
    { id: "destructive-confirmation", text: "Destructive confirmation", depth: 3 },
    { id: "sizes", text: "Sizes", depth: 3 },
    { id: "controlled", text: "Controlled", depth: 3 },
    { id: "a-form-in-a-dialog", text: "A form in a dialog", depth: 3 },
    { id: "nested-dialogs", text: "Nested dialogs", depth: 3 },
    { id: "scrolling-outside-the-dialog", text: "Scrolling outside the dialog", depth: 3 },
    { id: "scrolling-inside-the-dialog", text: "Scrolling inside the dialog", depth: 3 },
    { id: "elements-outside-the-popup", text: "Elements outside the popup", depth: 3 },
    { id: "programmatic-dialogs", text: "Programmatic dialogs", depth: 2 },
    { id: "setup", text: "Setup", depth: 3 },
    { id: "the-three-built-ins", text: "The three built-ins", depth: 3 },
    { id: "dialogs-of-your-own", text: "Dialogs of your own", depth: 3 },
    { id: "stacking", text: "Stacking", depth: 3 },
    { id: "outside-react", text: "Outside React", depth: 3 },
    { id: "what-settles-the-promise", text: "What settles the promise", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "motion", text: "Motion", depth: 3 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "dialogtrigger", text: "Dialog.Trigger", depth: 3 },
    { id: "alertdialogtrigger", text: "AlertDialog.Trigger", depth: 3 },
    { id: "dialogpopup", text: "Dialog.Popup", depth: 3 },
    { id: "dialogsurface", text: "Dialog.Surface", depth: 3 },
    { id: "dialogtitle", text: "Dialog.Title", depth: 3 },
    { id: "dialogdescription", text: "Dialog.Description", depth: 3 },
    { id: "dialogclose", text: "Dialog.Close", depth: 3 },
    { id: "dialogfooter", text: "Dialog.Footer", depth: 3 },
    { id: "dialogroot-and-alertdialogroot", text: "Dialog.Root and AlertDialog.Root", depth: 3 },
    { id: "usedialog", text: "useDialog()", depth: 3 },
    { id: "dialogprovider", text: "Dialog.Provider", depth: 3 },
    { id: "built-in-dialog-options", text: "Built-in dialog options", depth: 3 },
    { id: "dialoglabels", text: "DialogLabels", depth: 3 },
    { id: "customdialogprops", text: "CustomDialogProps", depth: 3 },
    { id: "dialogcreatemanager", text: "Dialog.createManager()", depth: 3 },
  ],
  "/components/drawer": [
    { id: "import", text: "Import", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "sides", text: "Sides", depth: 3 },
    { id: "sizes", text: "Sizes", depth: 3 },
    { id: "floating", text: "Floating", depth: 3 },
    { id: "long-content", text: "Long content", depth: 3 },
    { id: "controlled", text: "Controlled", depth: 3 },
    { id: "nested-drawers", text: "Nested drawers", depth: 3 },
    { id: "snap-points", text: "Snap points", depth: 3 },
    { id: "swipe-to-open", text: "Swipe to open", depth: 3 },
    { id: "turning-the-gesture-off", text: "Turning the gesture off", depth: 3 },
    { id: "selecting-text", text: "Selecting text", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "software-keyboards", text: "Software keyboards", depth: 3 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "motion", text: "Motion", depth: 2 },
    { id: "reduced-motion", text: "Reduced motion", depth: 3 },
    { id: "one-rule-set-four-sides", text: "One rule set, four sides", depth: 3 },
    { id: "the-skirt", text: "The skirt", depth: 3 },
    { id: "swipe-velocity", text: "Swipe velocity", depth: 3 },
    { id: "how-a-stacked-parent-recedes", text: "How a stacked parent recedes", depth: 3 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "drawerroot", text: "Drawer.Root", depth: 3 },
    { id: "drawertrigger", text: "Drawer.Trigger", depth: 3 },
    { id: "drawerpopup", text: "Drawer.Popup", depth: 3 },
    { id: "drawerhandle", text: "Drawer.Handle", depth: 3 },
    { id: "drawercontent", text: "Drawer.Content", depth: 3 },
    { id: "drawertitle", text: "Drawer.Title", depth: 3 },
    { id: "drawerdescription", text: "Drawer.Description", depth: 3 },
    { id: "drawerclose", text: "Drawer.Close", depth: 3 },
    { id: "drawerfooter", text: "Drawer.Footer", depth: 3 },
    { id: "drawerswipearea", text: "Drawer.SwipeArea", depth: 3 },
    { id: "drawervirtualkeyboardprovider", text: "Drawer.VirtualKeyboardProvider", depth: 3 },
    { id: "drawercreatehandle", text: "Drawer.createHandle", depth: 3 },
  ],
  "/components/field": [
    { id: "import", text: "Import", depth: 2 },
    { id: "anatomy", text: "Anatomy", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "validation", text: "Validation", depth: 3 },
    { id: "custom-rules", text: "Custom rules", depth: 3 },
    { id: "checkboxes-and-switches", text: "Checkboxes and switches", depth: 3 },
    { id: "with-a-select", text: "With a Select", depth: 3 },
    { id: "groups", text: "Groups", depth: 3 },
    { id: "state", text: "State", depth: 2 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "fieldroot", text: "Field.Root", depth: 3 },
    { id: "fieldlabel", text: "Field.Label", depth: 3 },
    { id: "fielddescription", text: "Field.Description", depth: 3 },
    { id: "fielderror", text: "Field.Error", depth: 3 },
    { id: "fielditem", text: "Field.Item", depth: 3 },
    { id: "fieldvalidity", text: "Field.Validity", depth: 3 },
  ],
  "/components/fieldset": [
    { id: "import", text: "Import", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "disabled", text: "Disabled", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "fieldsetroot", text: "Fieldset.Root", depth: 3 },
    { id: "fieldsetlegend", text: "Fieldset.Legend", depth: 3 },
  ],
  "/components/form": [
    { id: "import", text: "Import", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "server-errors", text: "Server errors", depth: 3 },
    { id: "validation-timing", text: "Validation timing", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "form-1", text: "Form", depth: 3 },
  ],
  "/components/input": [
    { id: "import", text: "Import", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "sizes", text: "Sizes", depth: 3 },
    { id: "variants", text: "Variants", depth: 3 },
    { id: "states", text: "States", depth: 3 },
    { id: "multi-line", text: "Multi-line", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "input-1", text: "Input", depth: 3 },
  ],
  "/components/menu": [
    { id: "import", text: "Import", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "triggers", text: "Triggers", depth: 3 },
    { id: "icons-and-shortcuts", text: "Icons and shortcuts", depth: 3 },
    { id: "checkable-rows", text: "Checkable rows", depth: 3 },
    { id: "groups", text: "Groups", depth: 3 },
    { id: "submenus", text: "Submenus", depth: 3 },
    { id: "links", text: "Links", depth: 3 },
    { id: "placement", text: "Placement", depth: 3 },
    { id: "disabled", text: "Disabled", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "menuroot", text: "Menu.Root", depth: 3 },
    { id: "menutrigger", text: "Menu.Trigger", depth: 3 },
    { id: "menupopup", text: "Menu.Popup", depth: 3 },
    { id: "menuitem", text: "Menu.Item", depth: 3 },
    { id: "menulinkitem", text: "Menu.LinkItem", depth: 3 },
    { id: "menucheckboxitem", text: "Menu.CheckboxItem", depth: 3 },
    { id: "menuradiogroup", text: "Menu.RadioGroup", depth: 3 },
    { id: "menuradioitem", text: "Menu.RadioItem", depth: 3 },
    { id: "menugroup", text: "Menu.Group", depth: 3 },
    { id: "menugrouplabel", text: "Menu.GroupLabel", depth: 3 },
    { id: "menuseparator", text: "Menu.Separator", depth: 3 },
    { id: "menusubmenuroot", text: "Menu.SubmenuRoot", depth: 3 },
    { id: "menusubmenutrigger", text: "Menu.SubmenuTrigger", depth: 3 },
    { id: "menushortcut", text: "Menu.Shortcut", depth: 3 },
  ],
  "/components/menubar": [
    { id: "import", text: "Import", depth: 2 },
    { id: "anatomy", text: "Anatomy", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "variants", text: "Variants", depth: 3 },
    { id: "an-application-bar", text: "An application bar", depth: 3 },
    { id: "triggers", text: "Triggers", depth: 3 },
    { id: "vertical", text: "Vertical", depth: 3 },
    { id: "disabled", text: "Disabled", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "menubar-1", text: "Menubar", depth: 3 },
  ],
  "/components/navigation-menu": [
    { id: "import", text: "Import", depth: 2 },
    { id: "anatomy", text: "Anatomy", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "two-variants-two-parts", text: "Two variants, two parts", depth: 3 },
    { id: "columns", text: "Columns", depth: 3 },
    { id: "an-arrow", text: "An arrow", depth: 3 },
    { id: "the-current-page", text: "The current page", depth: 3 },
    { id: "vertical", text: "Vertical", depth: 3 },
    { id: "nested-menus", text: "Nested menus", depth: 3 },
    { id: "controlled", text: "Controlled", depth: 3 },
    { id: "client-side-routing", text: "Client-side routing", depth: 3 },
    { id: "placement", text: "Placement", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "motion", text: "Motion", depth: 3 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "navigationmenuroot", text: "NavigationMenu.Root", depth: 3 },
    { id: "navigationmenulist", text: "NavigationMenu.List", depth: 3 },
    { id: "navigationmenuitem", text: "NavigationMenu.Item", depth: 3 },
    { id: "navigationmenutrigger", text: "NavigationMenu.Trigger", depth: 3 },
    { id: "navigationmenuicon", text: "NavigationMenu.Icon", depth: 3 },
    { id: "navigationmenucontent", text: "NavigationMenu.Content", depth: 3 },
    { id: "navigationmenulink", text: "NavigationMenu.Link", depth: 3 },
    { id: "navigationmenulinktitle", text: "NavigationMenu.LinkTitle", depth: 3 },
    { id: "navigationmenulinkdescription", text: "NavigationMenu.LinkDescription", depth: 3 },
    { id: "navigationmenupopup", text: "NavigationMenu.Popup", depth: 3 },
  ],
  "/components/number-field": [
    { id: "import", text: "Import", depth: 2 },
    { id: "anatomy", text: "Anatomy", depth: 2 },
    { id: "scrubbing", text: "Scrubbing", depth: 2 },
    { id: "sensitivity-and-direction", text: "Sensitivity and direction", depth: 3 },
    { id: "the-wheel", text: "The wheel", depth: 3 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "sizes", text: "Sizes", depth: 3 },
    { id: "variants", text: "Variants", depth: 3 },
    { id: "formatting", text: "Formatting", depth: 3 },
    { id: "steps", text: "Steps", depth: 3 },
    { id: "states", text: "States", depth: 3 },
    { id: "in-a-form", text: "In a form", depth: 3 },
    { id: "keyboard", text: "Keyboard", depth: 2 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "numberfieldroot", text: "NumberField.Root", depth: 3 },
    { id: "numberfieldgroup", text: "NumberField.Group", depth: 3 },
    { id: "numberfieldinput", text: "NumberField.Input", depth: 3 },
    { id: "numberfieldincrement", text: "NumberField.Increment", depth: 3 },
    { id: "numberfielddecrement", text: "NumberField.Decrement", depth: 3 },
    { id: "numberfieldscrubarea", text: "NumberField.ScrubArea", depth: 3 },
    { id: "numberfieldscrubareacursor", text: "NumberField.ScrubAreaCursor", depth: 3 },
  ],
  "/components/otp-field": [
    { id: "import", text: "Import", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "sizes", text: "Sizes", depth: 3 },
    { id: "variants", text: "Variants", depth: 3 },
    { id: "grouped", text: "Grouped", depth: 3 },
    { id: "masking-and-character-set", text: "Masking and character set", depth: 3 },
    { id: "states", text: "States", depth: 3 },
    { id: "auto-submit", text: "Auto-submit", depth: 3 },
    { id: "controlled", text: "Controlled", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "otpfieldroot", text: "OTPField.Root", depth: 3 },
    { id: "otpfieldinput", text: "OTPField.Input", depth: 3 },
    { id: "otpfieldseparator", text: "OTPField.Separator", depth: 3 },
  ],
  "/components/popover": [
    { id: "popover-or-tooltip", text: "Popover or tooltip?", depth: 2 },
    { id: "import", text: "Import", depth: 2 },
    { id: "anatomy", text: "Anatomy", depth: 2 },
    { id: "the-arrow", text: "The arrow", depth: 3 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "sides", text: "Sides", depth: 3 },
    { id: "sizes", text: "Sizes", depth: 3 },
    { id: "opening-on-hover", text: "Opening on hover", depth: 3 },
    { id: "a-form-inside", text: "A form inside", depth: 3 },
    { id: "modal", text: "Modal", depth: 3 },
    { id: "tall-content", text: "Tall content", depth: 3 },
    { id: "multiple-triggers", text: "Multiple triggers", depth: 3 },
    { id: "detached-triggers", text: "Detached triggers", depth: 3 },
    { id: "controlled-with-multiple-triggers", text: "Controlled, with multiple triggers", depth: 3 },
    { id: "animating-between-triggers", text: "Animating between triggers", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "popoverroot", text: "Popover.Root", depth: 3 },
    { id: "popovertrigger", text: "Popover.Trigger", depth: 3 },
    { id: "popoverpopup", text: "Popover.Popup", depth: 3 },
    { id: "popoverarrow", text: "Popover.Arrow", depth: 3 },
    { id: "popovertitle", text: "Popover.Title", depth: 3 },
    { id: "popoverdescription", text: "Popover.Description", depth: 3 },
    { id: "popoverclose", text: "Popover.Close", depth: 3 },
    { id: "popoverfooter", text: "Popover.Footer", depth: 3 },
    { id: "popoverviewport", text: "Popover.Viewport", depth: 3 },
    { id: "popovercreatehandle", text: "Popover.createHandle", depth: 3 },
  ],
  "/components/preview-card": [
    { id: "preview-card-popover-or-tooltip", text: "Preview card, popover, or tooltip?", depth: 2 },
    { id: "import", text: "Import", depth: 2 },
    { id: "anatomy", text: "Anatomy", depth: 2 },
    { id: "the-trigger-is-a-link", text: "The trigger is a link", depth: 3 },
    { id: "the-arrow", text: "The arrow", depth: 3 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "sides", text: "Sides", depth: 3 },
    { id: "sizes", text: "Sizes", depth: 3 },
    { id: "timing", text: "Timing", depth: 3 },
    { id: "beyond-a-profile", text: "Beyond a profile", depth: 3 },
    { id: "multiple-links-one-card", text: "Multiple links, one card", depth: 3 },
    { id: "animating-between-links", text: "Animating between links", depth: 3 },
    { id: "controlled", text: "Controlled", depth: 3 },
    { id: "detached-triggers", text: "Detached triggers", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "previewcardroot", text: "PreviewCard.Root", depth: 3 },
    { id: "previewcardtrigger", text: "PreviewCard.Trigger", depth: 3 },
    { id: "previewcardpopup", text: "PreviewCard.Popup", depth: 3 },
    { id: "previewcardarrow", text: "PreviewCard.Arrow", depth: 3 },
    { id: "previewcardviewport", text: "PreviewCard.Viewport", depth: 3 },
    { id: "previewcardcreatehandle", text: "PreviewCard.createHandle", depth: 3 },
  ],
  "/components/progress": [
    { id: "import", text: "Import", depth: 2 },
    { id: "which-one", text: "Which one", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "anatomy", text: "Anatomy", depth: 3 },
    { id: "indeterminate", text: "Indeterminate", depth: 3 },
    { id: "sizes", text: "Sizes", depth: 3 },
    { id: "tones", text: "Tones", depth: 3 },
    { id: "formatting-the-value", text: "Formatting the value", depth: 3 },
    { id: "reduced-motion", text: "Reduced motion", depth: 3 },
    { id: "theming", text: "Theming", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "theming-1", text: "Theming", depth: 2 },
    { id: "progress-1", text: "Progress", depth: 3 },
    { id: "progresscircle", text: "ProgressCircle", depth: 3 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "progressroot", text: "Progress.Root", depth: 3 },
    { id: "progresslabel", text: "Progress.Label", depth: 3 },
    { id: "progressvalue", text: "Progress.Value", depth: 3 },
    { id: "progresstrack", text: "Progress.Track", depth: 3 },
    { id: "progressindicator", text: "Progress.Indicator", depth: 3 },
    { id: "progresscircleroot", text: "ProgressCircle.Root", depth: 3 },
    { id: "progresscircletrack", text: "ProgressCircle.Track", depth: 3 },
    { id: "progresscircleindicator", text: "ProgressCircle.Indicator", depth: 3 },
    { id: "progresscirclevalue", text: "ProgressCircle.Value", depth: 3 },
    { id: "progresscirclelabel", text: "ProgressCircle.Label", depth: 3 },
  ],
  "/components/radio": [
    { id: "import", text: "Import", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "sizes", text: "Sizes", depth: 3 },
    { id: "orientation", text: "Orientation", depth: 3 },
    { id: "descriptions", text: "Descriptions", depth: 3 },
    { id: "controlled", text: "Controlled", depth: 3 },
    { id: "disabled-and-read-only", text: "Disabled and read-only", depth: 3 },
    { id: "labelling-a-group", text: "Labelling a group", depth: 3 },
    { id: "rendering-as-a-native-button", text: "Rendering as a native button", depth: 3 },
    { id: "in-a-form", text: "In a form", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "radio-1", text: "Radio", depth: 3 },
    { id: "radiogroup", text: "RadioGroup", depth: 3 },
  ],
  "/components/scroll-area": [
    { id: "import", text: "Import", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "vertical", text: "Vertical", depth: 3 },
    { id: "horizontal", text: "Horizontal", depth: 3 },
    { id: "both-scrollbars", text: "Both scrollbars", depth: 3 },
    { id: "scrollable-tabs", text: "Scrollable tabs", depth: 3 },
    { id: "always-visible-scrollbars-no-fade", text: "Always-visible scrollbars, no fade", depth: 3 },
    { id: "sizing", text: "Sizing", depth: 2 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "how-the-fade-works", text: "How the fade works", depth: 2 },
    { id: "motion", text: "Motion", depth: 3 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "scrollarearoot", text: "ScrollArea.Root", depth: 3 },
    { id: "scrollareaviewport", text: "ScrollArea.Viewport", depth: 3 },
    { id: "scrollareacontent", text: "ScrollArea.Content", depth: 3 },
    { id: "scrollareascrollbar", text: "ScrollArea.Scrollbar", depth: 3 },
    { id: "scrollareathumb", text: "ScrollArea.Thumb", depth: 3 },
    { id: "scrollareacorner", text: "ScrollArea.Corner", depth: 3 },
  ],
  "/components/select": [
    { id: "import", text: "Import", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "labelling", text: "Labelling", depth: 3 },
    { id: "grouped-options", text: "Grouped options", depth: 3 },
    { id: "sizes", text: "Sizes", depth: 3 },
    { id: "variants", text: "Variants", depth: 3 },
    { id: "disabled-items", text: "Disabled items", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "selectroot", text: "Select.Root", depth: 3 },
    { id: "selectlabel", text: "Select.Label", depth: 3 },
    { id: "selecttrigger", text: "Select.Trigger", depth: 3 },
    { id: "selectvalue", text: "Select.Value", depth: 3 },
    { id: "selecticon", text: "Select.Icon", depth: 3 },
    { id: "selectpopup", text: "Select.Popup", depth: 3 },
    { id: "selectitem", text: "Select.Item", depth: 3 },
    { id: "selectgroup", text: "Select.Group", depth: 3 },
    { id: "selectgrouplabel", text: "Select.GroupLabel", depth: 3 },
    { id: "selectseparator", text: "Select.Separator", depth: 3 },
  ],
  "/components/separator": [
    { id: "import", text: "Import", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "vertical", text: "Vertical", depth: 3 },
    { id: "line-style", text: "Line style", depth: 3 },
    { id: "spacing-and-inset", text: "Spacing and inset", depth: 3 },
    { id: "in-prose", text: "In prose", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
  ],
  "/components/slider": [
    { id: "import", text: "Import", depth: 2 },
    { id: "anatomy", text: "Anatomy", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "range-slider", text: "Range slider", depth: 3 },
    { id: "thumb-alignment", text: "Thumb alignment", depth: 3 },
    { id: "thumb-collision", text: "Thumb collision", depth: 3 },
    { id: "sizes", text: "Sizes", depth: 3 },
    { id: "tones", text: "Tones", depth: 3 },
    { id: "vertical", text: "Vertical", depth: 3 },
    { id: "form-integration", text: "Form integration", depth: 3 },
    { id: "disabled", text: "Disabled", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "contrast", text: "Contrast", depth: 3 },
    { id: "motion", text: "Motion", depth: 3 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "sliderroot", text: "Slider.Root", depth: 3 },
    { id: "sliderlabel", text: "Slider.Label", depth: 3 },
    { id: "slidervalue", text: "Slider.Value", depth: 3 },
    { id: "slidercontrol", text: "Slider.Control", depth: 3 },
    { id: "slidertrack", text: "Slider.Track", depth: 3 },
    { id: "sliderindicator", text: "Slider.Indicator", depth: 3 },
    { id: "sliderthumb", text: "Slider.Thumb", depth: 3 },
  ],
  "/components/spinner": [
    { id: "import", text: "Import", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "variants", text: "Variants", depth: 3 },
    { id: "sizes", text: "Sizes", depth: 3 },
    { id: "tones", text: "Tones", depth: 3 },
    { id: "label-and-placement", text: "Label and placement", depth: 3 },
    { id: "in-a-loading-panel", text: "In a loading panel", depth: 3 },
    { id: "reduced-motion", text: "Reduced motion", depth: 3 },
    { id: "theming", text: "Theming", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "theming-1", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
  ],
  "/components/switch": [
    { id: "import", text: "Import", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "sizes", text: "Sizes", depth: 3 },
    { id: "disabled", text: "Disabled", depth: 3 },
    { id: "settings-list", text: "Settings list", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "motion-under-prefers-reduced-motion", text: "Motion under prefers-reduced-motion", depth: 3 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
  ],
  "/components/tabs": [
    { id: "import", text: "Import", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "line", text: "Line", depth: 3 },
    { id: "pill", text: "Pill", depth: 3 },
    { id: "vertical", text: "Vertical", depth: 3 },
    { id: "with-icons", text: "With icons", depth: 3 },
    { id: "disabled-tab", text: "Disabled tab", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "motion", text: "Motion", depth: 3 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "tabsroot", text: "Tabs.Root", depth: 3 },
    { id: "tabslist", text: "Tabs.List", depth: 3 },
    { id: "tabstab", text: "Tabs.Tab", depth: 3 },
    { id: "tabsindicator", text: "Tabs.Indicator", depth: 3 },
    { id: "tabspanel", text: "Tabs.Panel", depth: 3 },
  ],
  "/components/textarea": [
    { id: "import", text: "Import", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "sizes", text: "Sizes", depth: 3 },
    { id: "variants", text: "Variants", depth: 3 },
    { id: "growing-with-the-content", text: "Growing with the content", depth: 3 },
    { id: "a-character-counter", text: "A character counter", depth: 3 },
    { id: "a-comment-composer", text: "A comment composer", depth: 3 },
    { id: "states", text: "States", depth: 3 },
    { id: "in-a-form", text: "In a form", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "textarea-1", text: "Textarea", depth: 3 },
  ],
  "/components/toast": [
    { id: "import", text: "Import", depth: 2 },
    { id: "setup", text: "Setup", depth: 2 },
    { id: "the-hook", text: "The hook", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "controlling-a-toast-after-it-appears", text: "Controlling a toast after it appears", depth: 3 },
    { id: "following-a-promise", text: "Following a promise", depth: 3 },
    { id: "an-action-button", text: "An action button", depth: 3 },
    { id: "stacking-and-how-long-a-toast-stays", text: "Stacking, and how long a toast stays", depth: 3 },
    { id: "position", text: "Position", depth: 3 },
    { id: "custom-contents", text: "Custom contents", depth: 3 },
    { id: "outside-react", text: "Outside React", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "motion", text: "Motion", depth: 3 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "usetoast", text: "useToast()", depth: 3 },
    { id: "toasthandle", text: "ToastHandle", depth: 3 },
    { id: "toastoptions", text: "ToastOptions", depth: 3 },
    { id: "toastcreatemanager", text: "Toast.createManager()", depth: 3 },
    { id: "toastprovider", text: "Toast.Provider", depth: 3 },
    { id: "toastviewport", text: "Toast.Viewport", depth: 3 },
    { id: "toastitem", text: "Toast.Item", depth: 3 },
    { id: "toasticon", text: "Toast.Icon", depth: 3 },
    { id: "toasttitle", text: "Toast.Title", depth: 3 },
    { id: "toastdescription", text: "Toast.Description", depth: 3 },
    { id: "toastaction", text: "Toast.Action", depth: 3 },
    { id: "toastclose", text: "Toast.Close", depth: 3 },
  ],
  "/components/toggle": [
    { id: "import", text: "Import", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "variants", text: "Variants", depth: 3 },
    { id: "tones", text: "Tones", depth: 3 },
    { id: "sizes", text: "Sizes", depth: 3 },
    { id: "icon-only", text: "Icon only", depth: 3 },
    { id: "swapping-the-icon-with-the-state", text: "Swapping the icon with the state", depth: 3 },
    { id: "controlled", text: "Controlled", depth: 3 },
    { id: "disabled", text: "Disabled", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "toggle-1", text: "Toggle", depth: 3 },
  ],
  "/components/toggle-group": [
    { id: "import", text: "Import", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "multiple", text: "Multiple", depth: 3 },
    { id: "segmented", text: "Segmented", depth: 3 },
    { id: "shared-appearance", text: "Shared appearance", depth: 3 },
    { id: "orientation", text: "Orientation", depth: 3 },
    { id: "controlled", text: "Controlled", depth: 3 },
    { id: "disabled", text: "Disabled", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "togglegroup", text: "ToggleGroup", depth: 3 },
    { id: "toggle", text: "Toggle", depth: 3 },
  ],
  "/components/toolbar": [
    { id: "import", text: "Import", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "groups-and-separators", text: "Groups and separators", depth: 3 },
    { id: "variants", text: "Variants", depth: 3 },
    { id: "sizes", text: "Sizes", depth: 3 },
    { id: "orientation", text: "Orientation", depth: 3 },
    { id: "menus-selects-and-toggles", text: "Menus, selects and toggles", depth: 3 },
    { id: "text-inputs", text: "Text inputs", depth: 3 },
    { id: "links", text: "Links", depth: 3 },
    { id: "disabled", text: "Disabled", depth: 3 },
    { id: "in-an-editor", text: "In an editor", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "group", text: "Group", depth: 3 },
    { id: "separator", text: "Separator", depth: 3 },
    { id: "link", text: "Link", depth: 3 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "toolbarroot", text: "Toolbar.Root", depth: 3 },
    { id: "toolbargroup", text: "Toolbar.Group", depth: 3 },
    { id: "toolbarbutton", text: "Toolbar.Button", depth: 3 },
    { id: "toolbarlink", text: "Toolbar.Link", depth: 3 },
    { id: "toolbarinput", text: "Toolbar.Input", depth: 3 },
    { id: "toolbarseparator", text: "Toolbar.Separator", depth: 3 },
  ],
  "/components/tooltip": [
    { id: "import", text: "Import", depth: 2 },
    { id: "examples", text: "Examples", depth: 2 },
    { id: "sides", text: "Sides", depth: 3 },
    { id: "shared-delay-across-a-toolbar", text: "Shared delay across a toolbar", depth: 3 },
    { id: "tuning-the-delay", text: "Tuning the delay", depth: 3 },
    { id: "accessibility", text: "Accessibility", depth: 2 },
    { id: "theming", text: "Theming", depth: 2 },
    { id: "api-reference", text: "API reference", depth: 2 },
    { id: "tooltipprovider", text: "Tooltip.Provider", depth: 3 },
    { id: "tooltiproot", text: "Tooltip.Root", depth: 3 },
    { id: "tooltiptrigger", text: "Tooltip.Trigger", depth: 3 },
    { id: "tooltippopup", text: "Tooltip.Popup", depth: 3 },
    { id: "tooltiparrow", text: "Tooltip.Arrow", depth: 3 },
  ],
  "/customization/presets": [
    { id: "radius", text: "Radius", depth: 2 },
    { id: "density", text: "Density", depth: 2 },
    { id: "motion", text: "Motion", depth: 2 },
    { id: "how-presets-and-scoped-themes-interact", text: "How presets and scoped themes interact", depth: 2 },
  ],
  "/customization/styling": [
    { id: "theming-knobs", text: "Theming knobs", depth: 2 },
    { id: "parts-and-states", text: "Parts and states", depth: 2 },
    { id: "what-you-take-on", text: "What you take on", depth: 2 },
    { id: "when-css-keeps-repeating-itself", text: "When CSS keeps repeating itself", depth: 2 },
  ],
  "/customization/tailwind": [
    { id: "setup", text: "Setup", depth: 2 },
    { id: "what-the-bridge-changes", text: "What the bridge changes", depth: 2 },
    { id: "targeting-component-state", text: "Targeting component state", depth: 2 },
    { id: "merging-classes-cn", text: "Merging classes: cn", depth: 2 },
  ],
  "/customization/theming": [
    { id: "the-seed", text: "The seed", depth: 2 },
    { id: "what-the-seed-derives", text: "What the seed derives", depth: 2 },
    { id: "text-on-your-brand-colour", text: "Text on your brand colour", depth: 2 },
    { id: "light-and-dark", text: "Light and dark", depth: 2 },
    { id: "scoped-themes", text: "Scoped themes", depth: 2 },
    { id: "where-to-go-next", text: "Where to go next", depth: 2 },
  ],
  "/customization/tokens": [
    { id: "how-to-override-a-token", text: "How to override a token", depth: 2 },
    { id: "colour", text: "Colour", depth: 2 },
    { id: "surfaces-text-and-borders", text: "Surfaces, text and borders", depth: 3 },
    { id: "brand", text: "Brand", depth: 3 },
    { id: "status", text: "Status", depth: 3 },
    { id: "focus-ring", text: "Focus ring", depth: 3 },
    { id: "spacing", text: "Spacing", depth: 2 },
    { id: "typography", text: "Typography", depth: 2 },
    { id: "radius", text: "Radius", depth: 2 },
    { id: "controls-and-density", text: "Controls and density", depth: 2 },
    { id: "elevation", text: "Elevation", depth: 2 },
    { id: "motion", text: "Motion", depth: 2 },
    { id: "for-tooling", text: "For tooling", depth: 2 },
  ],
};
